# Generated by Django 4.2.24 on 2025-10-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesessiontranslation",
            name="button",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
