# Generated by Django 4.2.24 on 2025-10-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_gamesessiontranslation_button"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("card", "Credit/Debit Card"),
                    ("bank_transfer", "Bank Transfer"),
                    ("revolut", "Revolut Pay"),
                ],
                default="card",
                max_length=20,
                null=True,
            ),
        ),
    ]
