# Generated by Django 4.2.24 on 2025-10-24 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_booking_options_booking_payment_method"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={},
        ),
        migrations.RemoveField(
            model_name="booking",
            name="payment_method",
        ),
    ]
