# Generated by Django 4.2.24 on 2025-10-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_booking_options_remove_booking_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("card", "Credit/Debit Card"),
                    ("revolut", "Revolut"),
                    ("paypal", "PayPal"),
                    ("cash", "Cash"),
                ],
                default="card",
                max_length=20,
            ),
        ),
    ]
