# Generated by Django 4.2.28 on 2026-03-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_booking_payment_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamesession",
            name="game_type",
        ),
        migrations.AddField(
            model_name="gamesession",
            name="collab",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
