# Generated by Django 4.2.28 on 2026-03-16 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_remove_gamesession_game_type_gamesession_collab"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="private",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="gamesession",
            name="max_participants",
            field=models.PositiveIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(20),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="gamesession",
            name="price_per_person",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
