# Generated by Django 4.2.28 on 2026-03-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_gamesession_private_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="address",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
