# Generated by Django 4.2.28 on 2026-04-24 04:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_event_booking_ticket_quantity_tickettype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesession",
            name="max_participants",
            field=models.PositiveIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(250),
                ],
            ),
        ),
    ]
