# Generated by Django 4.2.24 on 2025-10-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="principle",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
