# Generated by Django 4.2.24 on 2025-10-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sections", "0002_principle_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="principle",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="stat",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="stat",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
