# Generated by Django 4.2.24 on 2025-10-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sections", "0003_alter_principle_options_alter_stat_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bannertranslation",
            name="button1",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="bannertranslation",
            name="button2",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="headertranslation",
            name="button1",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="headertranslation",
            name="button2",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
