# Generated by Django 4.2.24 on 2026-01-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="employees/"),
        ),
    ]
