# Generated by Django 4.2.24 on 2026-01-27 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_employee_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactinfo",
            name="address",
        ),
        migrations.RemoveField(
            model_name="contactinfo",
            name="city",
        ),
        migrations.RemoveField(
            model_name="contactinfo",
            name="postal_code",
        ),
    ]
