# Generated by Django 4.2.24 on 2026-01-27 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_remove_contactinfo_address_remove_contactinfo_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactinfo",
            name="phone",
        ),
    ]
